#!/bin/sh

rm -f src/*.o src/*.so src/symbols.rds src/Makefile src/*.cmake src/CMakeCache.txt
rm -rf src/CMakefiles src/CPM_modules
rm inst/extdata/*transposed*
rm -rf src/_deps
rm -rf src/hwloc-prefix
rm -rf src/build
rm src/Makevars
rm src/Makevars.gen
