# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcppplanc_aoadmmnmf <- function(x, k, niter) {
    .Call(`_RcppPlanc_rcppplanc_aoadmmnmf`, x, k, niter)
}

rcppplanc_gnsymnmf <- function(x, k, niter) {
    .Call(`_RcppPlanc_rcppplanc_gnsymnmf`, x, k, niter)
}

rcppplanc_halsnmf <- function(x, k, niter) {
    .Call(`_RcppPlanc_rcppplanc_halsnmf`, x, k, niter)
}

rcppplanc_munmf <- function(x, k, niter) {
    .Call(`_RcppPlanc_rcppplanc_munmf`, x, k, niter)
}

rcppplanc_bppnmf <- function(x, k, niter) {
    .Call(`_RcppPlanc_rcppplanc_bppnmf`, x, k, niter)
}

rcppplanc_bppnnls <- function(A, B) {
    .Call(`_RcppPlanc_rcppplanc_bppnnls`, A, B)
}

