# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Alternating Direction Method of Multipliers NMF
#'
#' Use the AOADMM algorithm to factor a given matrix at the given rank.
#'
#' @param x Input matrix for factorization
#' @param k Factor matrix rank
#' @param niter Maximum number of nmf iterations
#' @param H_init Initial right-hand factor matrix (Optional)
#' @param W_init Initial left-hand factor matrix (Optional)
#' @export
#' @returns The calculated factor matrices as an Rcpp::List
#' @examplesIf require("Matrix")
#' aoadmmnmf(rsparsematrix(nrow = 100, ncol = 100, nnz = 10, symmetric = TRUE), 10, 10)
aoadmmnmf <- function(x, k, niter, W_init = NULL, H_init = NULL) {
    .Call(`_RcppPlanc_aoadmmnmf`, x, k, niter, W_init, H_init)
}

#' Gauss-Newton using Conjugate Gradients NMF
#'
#' Use the Gauss-Newton algorithm to factor a given matrix at the given rank.
#'
#' @param x Input matrix for factorization
#' @param k Factor matrix rank
#' @param niter Maximum number of nmf iterations
#' @param H_init Initial right-hand factor matrix (Optional)
#' @param W_init Initial left-hand factor matrix (Optional)
#' @export
#' @returns The calculated factor matrices as an Rcpp::List
#' @examplesIf require("Matrix")
#' gnsymnmf(rsparsematrix(nrow = 100, ncol = 100, nnz = 10, symmetric = TRUE), 10, 10)
gnsymnmf <- function(x, k, niter, W_init = NULL, H_init = NULL) {
    .Call(`_RcppPlanc_gnsymnmf`, x, k, niter, W_init, H_init)
}

#' Hierarchical Alternating Least Squares NMF
#'
#' Use the HALS algorithm to factor a given matrix at the given rank.
#'
#' @param x Input matrix for factorization
#' @param k Factor matrix rank
#' @param niter Maximum number of nmf iterations
#' @param H_init Initial right-hand factor matrix (Optional)
#' @param W_init Initial left-hand factor matrix (Optional)
#' @export
#' @returns The calculated factor matrices as an Rcpp::List
#' @examplesIf require("Matrix")
#' halsmnmf(rsparsematrix(nrow = 100, ncol = 100, nnz = 10, symmetric = TRUE), 10, 10)
halsnmf <- function(x, k, niter, W_init = NULL, H_init = NULL) {
    .Call(`_RcppPlanc_halsnmf`, x, k, niter, W_init, H_init)
}

#' Multiplicative Update NMF
#'
#' Use the MU algorithm to factor a given matrix
#' at the given rank.
#' @param x Input matrix for factorization
#' @param k Factor matrix rank
#' @param niter Maximum number of nmf iterations
#' @param H_init Initial right-hand factor matrix (Optional)
#' @param W_init Initial left-hand factor matrix (Optional)
#' @export
#' @returns The calculated factor matrices as an Rcpp::List
#' @examplesIf require("Matrix")
#' halsnmf(rsparsematrix(nrow = 100, ncol = 100, nnz = 10, symmetric = TRUE), 10, 10)
munmf <- function(x, k, niter, W_init = NULL, H_init = NULL) {
    .Call(`_RcppPlanc_munmf`, x, k, niter, W_init, H_init)
}

#' Alternating  Nonnegative Least Squares with Block Principal Pivoting NMF
#'
#' Use the ANLS-BPP algorithm to factor a given matrix at the given rank.
#'
#' @param x Input matrix for factorization
#' @param k Factor matrix rank
#' @param niter Maximum number of nmf iterations
#' @param H_init Initial right-hand factor matrix (Optional)
#' @param W_init Initial left-hand factor matrix (Optional)
#' @export
#' @returns The calculated factor matrices as an Rcpp::List
#' @examplesIf require("Matrix")
#' munmf(rsparsematrix(nrow = 100, ncol = 100, nnz = 10, symmetric = TRUE), 10, 10)
bppnmf <- function(x, k, niter, W_init = NULL, H_init = NULL) {
    .Call(`_RcppPlanc_bppnmf`, x, k, niter, W_init, H_init)
}

#' Block Principal Pivoted Non-Negative Least Squares
#'
#' Use the BPP algorithm to get the nonnegative least squares solution for the given matrices.
#'
#' @param C Input factor dense matrix
#' @param B Input sparse matrix
#' @export
#' @returns The calculated solution matrix in dense form.
bppnnls <- function(C, B) {
    .Call(`_RcppPlanc_bppnnls`, C, B)
}

#' Block Principal Pivoted Iterative Non-Negative Matrix Factorization
#'
#' Use the BPP algorithm to iteratively factor the given datasets.
#'
#' @param Ei List of datasets in dense matrix form.
#' @export
#' @returns The calculated solution matrix in dense form.
#' @examplesIf require("Matrix")
#' bppinmf(rsparsematrix(nrow=20,ncol=20,nnz=10), Matrix(runif(n=200,min=0,max=2),20,10))
bppinmf <- function(objectList, k, lambda, maxIter, thresh) {
    .Call(`_RcppPlanc_bppinmf`, objectList, k, lambda, maxIter, thresh)
}

#' @export
bppinmf_sparse <- function(objectList, k, lambda, maxIter, thresh, Hinit = NULL, Vinit = NULL, Winit = NULL) {
    .Call(`_RcppPlanc_bppinmf_sparse`, objectList, k, lambda, maxIter, thresh, Hinit, Vinit, Winit)
}

